/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List entries with optional filtering and pagination */
        get: operations["listEntries"];
        put?: never;
        /** Create a new entry */
        post: operations["createEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a single entry */
        get: operations["getEntry"];
        put?: never;
        post?: never;
        /** Soft-delete an entry */
        delete: operations["deleteEntry"];
        options?: never;
        head?: never;
        /** Update an entry */
        patch: operations["updateEntry"];
        trace?: never;
    };
    "/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all collections */
        get: operations["listCollections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a single collection */
        get: operations["getCollection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all tags */
        get: operations["listTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a single tag */
        get: operations["getTag"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Entry: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @enum {string} */
            kind: "task" | "note" | "event";
            /** @description ISO date or datetime; null means inbox */
            start?: string | null;
            /** @enum {string} */
            period?: "day" | "week" | "month" | "year";
            importance?: number | null;
            /** @enum {string} */
            status: "not_started" | "completed" | "cancelled";
            /** Format: uuid */
            collection_id?: string | null;
            tag_ids?: string[];
            collection?: components["schemas"]["Collection"];
            tags?: components["schemas"]["Tag"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Collection: {
            /** Format: uuid */
            id: string;
            title: string;
            color?: string | null;
            /** Format: uuid */
            parent_id?: string | null;
            archived: boolean;
        };
        Tag: {
            /** Format: uuid */
            id: string;
            label: string;
            color?: string | null;
            archived: boolean;
        };
        PaginatedResponse: {
            data: unknown[];
            cursor?: string | null;
            has_more: boolean;
        };
        CreateEntryRequest: {
            title: string;
            /** @enum {string} */
            kind: "task" | "note" | "event";
            /** @description ISO date or datetime; omit for inbox */
            start?: string;
            /**
             * @default day
             * @enum {string}
             */
            period?: "day" | "week" | "month" | "year";
            importance?: number;
        };
        UpdateEntryRequest: {
            title?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listEntries: {
        parameters: {
            query?: {
                view?: "inbox" | "overdue";
                /** @description Valid only without views */
                period?: "day" | "week" | "month" | "year";
                /** @description YYYY-MM-DD, YYYY-MM, or YYYY */
                date?: string;
                status?: "not_started" | "completed" | "cancelled";
                kind?: "task" | "note" | "event";
                /** @description UUID(s) */
                collection?: string | string[];
                /** @description UUID(s) */
                tag?: string | string[];
                limit?: number;
                cursor?: string;
                expand?: "collection" | "tags";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse"] & {
                        data?: components["schemas"]["Entry"][];
                    };
                };
            };
        };
    };
    createEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntryRequest"];
            };
        };
        responses: {
            /** @description Created entry */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
        };
    };
    getEntry: {
        parameters: {
            query?: {
                expand?: "collection" | "tags";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entry object */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
        };
    };
    deleteEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted (succeeds even if already deleted) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEntryRequest"];
            };
        };
        responses: {
            /** @description Updated entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
        };
    };
    listCollections: {
        parameters: {
            query?: {
                archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wrapped array of collections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Collection"][];
                    };
                };
            };
        };
    };
    getCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collection object */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
        };
    };
    listTags: {
        parameters: {
            query?: {
                archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wrapped array of tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Tag"][];
                    };
                };
            };
        };
    };
    getTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag object */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
        };
    };
}
